# Generated by Django 3.2.12 on 2022-04-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_paymentmodel_usercoursemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentModel',
        ),
    ]
