# Generated by Django 3.2.12 on 2022-04-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_paymentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentModel',
        ),
    ]
